# Generated by Django 4.1.2 on 2022-11-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenmind', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='flag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='item_owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='item_url',
        ),
    ]
