# Generated by Django 4.1.2 on 2022-12-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenmind', '0004_rename_item_owner_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
