# Generated by Django 4.1.2 on 2022-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenmind', '0006_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
